image: python:3.9  

stages:
  - lint
  - test

before_script:
  - echo "Installation des requis"
  - pip install pylint

lint:
  stage: lint
  allow_failure: true
  script:
    - /home/isen/.local/bin/pylint gaussian_sum_formula.py   

unittest:
  stage: test
  script:
    - python3 -m unittest test_gaussian_sum_formula.py

